
-- Generated by ORDS REST Data Services 19.1.1.r1081514
-- Schema: DEVELOPER  Date: Mon Oct 28 04:54:25 2019 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'DEVELOPER',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'DEVELOPER',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'salesAPI',
      p_base_path      => '/sales/',
      p_items_per_page => 100,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'salesAPI',
      p_pattern        => 'stores',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'salesAPI',
      p_pattern        => 'stores',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select * from OOW_DEMO_STORES where STORE_TYPE =''Branch''');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'salesAPI',
      p_pattern        => 'transactions',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'salesAPI',
      p_pattern        => 'transactions',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'begin
    INSERT INTO OOW_DEMO_SALES_HISTORY 
    (STORE_ID, PRODUCT_ID, QUANTITY,TRANSACTION_ID,ITEM_PRICE,DATE_OF_SALE)
    VALUES 
    (:STORE_ID, :PRODUCT_ID, :QUANTITY,:TRANSACTION_ID,:ITEM_PRICE,CURRENT_TIMESTAMP);
    :status := 200;
    :id := :TRANSACTION_ID;
exception
    when others then
        :status := 400;
end;    ');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'salesAPI',
      p_pattern            => 'transactions',
      p_method             => 'POST',
      p_name               => 'QUANTITY',
      p_bind_variable_name => 'QUANTITY',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'salesAPI',
      p_pattern            => 'transactions',
      p_method             => 'POST',
      p_name               => 'id',
      p_bind_variable_name => 'id',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'salesAPI',
      p_pattern            => 'transactions',
      p_method             => 'POST',
      p_name               => 'TRANSACTION_ID',
      p_bind_variable_name => 'TRANSACTION_ID',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'salesAPI',
      p_pattern            => 'transactions',
      p_method             => 'POST',
      p_name               => 'ITEM_PRICE',
      p_bind_variable_name => 'ITEM_PRICE',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'salesAPI',
      p_pattern            => 'transactions',
      p_method             => 'POST',
      p_name               => 'STORE_ID',
      p_bind_variable_name => 'STORE_ID',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'salesAPI',
      p_pattern            => 'transactions',
      p_method             => 'POST',
      p_name               => 'PRODUCT_ID',
      p_bind_variable_name => 'PRODUCT_ID',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'salesAPI',
      p_pattern        => 'transactions',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select * from OOW_DEMO_SALES_HISTORY');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'salesAPI',
      p_pattern        => 'prediction/{store_id}',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'salesAPI',
      p_pattern        => 'prediction/{store_id}',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select ST.STORE_NAME, ST.STORE_ADDRESS, IT.ITEM_NAME, TO_CHAR(IT.MSRP, ''$9,999.00'') AS MSRP, IT.TYPE, AVG(PRED.SALE_PREDICTION) AS PREDICTED_QUANTITY_NEXT_WEEK
from OOW_DEMO_STORES ST, OOW_DEMO_ITEMS IT,ITEM_SOLD_PREDICTION_NEXT_WEEK PRED
where ST.ID=PRED.STORE_ID and IT.ID=PRED.PRODUCT_ID and ST.ID=:store_id
GROUP BY ST.STORE_NAME, ST.STORE_ADDRESS, IT.ITEM_NAME, IT.MSRP, IT.TYPE');

    
        
COMMIT;

END;